# Generated by Django 3.1.2 on 2021-01-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=250)),
                ('keyWords', models.CharField(max_length=25)),
                ('shortDescription', models.CharField(blank=True, max_length=500)),
                ('longDescription', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(default='', upload_to='event')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('sName', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='', upload_to='org')),
                ('about', models.CharField(blank=True, max_length=500)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='shop.event')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('linkedein', models.CharField(blank=True, max_length=100)),
                ('organizerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='shop.organizer')),
            ],
        ),
    ]
