# Generated by Django 3.1.2 on 2020-12-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='eventTitle',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='keyWord',
            new_name='keyWords',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='longDescription',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='event',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
