# Generated by Django 3.1.2 on 2020-12-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201222_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endData',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startData',
            new_name='startDate',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='static/frontend/'),
        ),
    ]
