# Generated by Django 3.1.2 on 2020-12-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201222_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='event'),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('sName', models.CharField(max_length=20)),
                ('about', models.CharField(blank=True, max_length=100)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.event')),
            ],
        ),
    ]
