# Generated by Django 3.1.2 on 2020-12-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201222_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='photo',
            field=models.ImageField(default='', upload_to='org'),
        ),
        migrations.AlterField(
            model_name='event',
            name='longDescription',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='about',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='shop.event'),
        ),
    ]
