# Generated by Django 3.1.2 on 2020-12-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201223_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('vk', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('linkedein', models.CharField(blank=True, max_length=100)),
                ('organizerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='shop.organizer')),
            ],
        ),
    ]
