# Generated by Django 3.1.2 on 2020-12-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sociallinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallinks',
            old_name='vk',
            new_name='twitter',
        ),
    ]
