# Generated by Django 3.1.2 on 2021-01-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('sName', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='', upload_to='org')),
                ('about', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketType', models.CharField(max_length=50)),
                ('info', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketTitle', models.CharField(max_length=250)),
                ('image', models.ImageField(default='', upload_to='ticket')),
                ('keyWords', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numLeft', models.PositiveIntegerField(default=0)),
                ('numMax', models.PositiveIntegerField(default=0)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('ticketType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket.type')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticketdetail')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('linkedein', models.CharField(blank=True, max_length=100)),
                ('organizerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ticket.organizer')),
            ],
        ),
        migrations.AddField(
            model_name='organizer',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='ticket.ticketdetail'),
        ),
    ]
