# Generated by Django 3.1.2 on 2021-01-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketTitle', models.CharField(max_length=250)),
                ('image', models.ImageField(default='', upload_to='ticket')),
                ('keyWords', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numLeft', models.PositiveIntegerField(default=0)),
                ('numMax', models.PositiveIntegerField(default=0)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('ticketType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='ticket.type')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_detail', to='ticket.ticketdetail')),
            ],
        ),
    ]
